const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('depk', {
  isElectron: true,
  scanDir: (root) => ipcRenderer.invoke('depk:scanDir', root),
  getDrives: () => ipcRenderer.invoke('depk:getDrives'),
  getProcesses: () => ipcRenderer.invoke('depk:getProcesses'),
  killProcess: (pid) => ipcRenderer.invoke('depk:killProcess', pid),
  getStartup: () => ipcRenderer.invoke('depk:getStartup'),
  getSysInfo: () => ipcRenderer.invoke('depk:getSysInfo'),
  getNetConns: () => ipcRenderer.invoke('depk:getNetConns'),
  getSoftware: () => ipcRenderer.invoke('depk:getSoftware'),
  getFirewallRules: () => ipcRenderer.invoke('depk:getFirewallRules'),
  quarantineFile: (path, verdict) => ipcRenderer.invoke('depk:quarantine', { path, verdict }),
  listQuarantine: () => ipcRenderer.invoke('depk:listQ'),
  restoreQuarantine: (id) => ipcRenderer.invoke('depk:restoreQ', id),
  deleteQuarantine: (id) => ipcRenderer.invoke('depk:deleteQ', id),
  watchStart: (dirs) => ipcRenderer.invoke('depk:watchStart', dirs),
  watchStop: () => ipcRenderer.invoke('depk:watchStop'),
  dynSandbox: (path, seconds) => ipcRenderer.invoke('depk:dynSandbox', { path, seconds }),
  pickFile: () => ipcRenderer.invoke('depk:pickFile'),
  onWatchEvent: (cb) => ipcRenderer.on('depk:watchEvent', (_e, d) => cb(d)),
  getStatus: () => ipcRenderer.invoke('setup:getStatus'),
  install: (dir, autostart) => ipcRenderer.invoke('setup:install', { dir, autostart }),
  uninstall: (dir) => ipcRenderer.invoke('setup:uninstall', { dir }),
  pickDir: () => ipcRenderer.invoke('setup:pickDir'),
  launchInstalled: () => ipcRenderer.invoke('setup:launchInstalled'),
  minWin: () => ipcRenderer.send('win:min'),
  closeWin: () => ipcRenderer.send('win:close'),
  onProgress: (cb) => ipcRenderer.on('setup:progress', (_e, d) => cb(d)),
  uninstallApp: (cmd, quiet) => ipcRenderer.invoke('depk:uninstallApp', { cmd, quiet }),
  forceRemove: (key, name, location) => ipcRenderer.invoke('depk:forceRemove', { key, name, location }),
  scanResidual: (name, location) => ipcRenderer.invoke('depk:scanResidual', { name, location }),
  deleteResidual: (paths) => ipcRenderer.invoke('depk:deleteResidual', { paths }),
  openLocation: (p) => ipcRenderer.invoke('depk:openLocation', p),
  copyText: (t) => ipcRenderer.invoke('depk:copyText', t),
  privacyGetStatus: () => ipcRenderer.invoke('privacy:status'),
  privacySet: (dev, deny) => ipcRenderer.invoke('privacy:set', { dev, deny }),
  privacyKill: (name) => ipcRenderer.invoke('privacy:kill', name),
  ctxStatus: () => ipcRenderer.invoke('depk:ctxStatus'),
  ctxSet: (on) => ipcRenderer.invoke('depk:ctxSet', on),
  scanJunk: () => ipcRenderer.invoke('maintain:scanJunk'),
  cleanJunk: (ids) => ipcRenderer.invoke('maintain:cleanJunk', ids),
  toggleStartup: (name, hive, command, enabled) => ipcRenderer.invoke('depk:toggleStartup', { name, hive, command, enabled }),
  failedLogons: () => ipcRenderer.invoke('auth:failedLogons'),
  killSwitch: () => ipcRenderer.invoke('net:killSwitch'),
  restoreNet: () => ipcRenderer.invoke('net:restoreNet'),
  usbList: () => ipcRenderer.invoke('depk:usbList'),
  checkUpdate: () => ipcRenderer.invoke('updater:checkNow'),
  updateState: () => ipcRenderer.invoke('updater:getState'),
  openUrl: (url) => ipcRenderer.invoke('sys:openUrl', url),
  quitApp: () => ipcRenderer.invoke('sys:quitApp'),
  onScanTarget: (cb) => ipcRenderer.on('depk:scanTarget', (_e, p) => cb(p)),
  onUsbInserted: (cb) => ipcRenderer.on('depk:usbInserted', (_e, d) => cb(d)),
  onUpdateAvailable: (cb) => ipcRenderer.on('depk:updateAvailable', (_e, d) => cb(d)),
  onUpdateNotify: (cb) => ipcRenderer.on('depk:updateNotify', (_e, d) => cb(d)),
  homeProt: () => ipcRenderer.invoke('web:homeProt'),
  homeFix: (id) => ipcRenderer.invoke('web:homeFix', id)
});
