const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('depk', {
  isElectron: true,
  scanDir: (root) => ipcRenderer.invoke('depk:scanDir', root),
  getDrives: () => ipcRenderer.invoke('depk:getDrives'),
  getProcesses: () => ipcRenderer.invoke('depk:getProcesses'),
  killProcess: (pid) => ipcRenderer.invoke('depk:killProcess', pid),
  getStartup: () => ipcRenderer.invoke('depk:getStartup'),
  getSysInfo: () => ipcRenderer.invoke('depk:getSysInfo'),
  getNetConns: () => ipcRenderer.invoke('depk:getNetConns'),
  getSoftware: () => ipcRenderer.invoke('depk:getSoftware'),
  getFirewallRules: () => ipcRenderer.invoke('depk:getFirewallRules'),
  quarantineFile: (path, verdict) => ipcRenderer.invoke('depk:quarantine', { path, verdict }),
  listQuarantine: () => ipcRenderer.invoke('depk:listQ'),
  restoreQuarantine: (id) => ipcRenderer.invoke('depk:restoreQ', id),
  deleteQuarantine: (id) => ipcRenderer.invoke('depk:deleteQ', id),
  watchStart: (dirs) => ipcRenderer.invoke('depk:watchStart', dirs),
  watchStop: () => ipcRenderer.invoke('depk:watchStop'),
  dynSandbox: (path, seconds) => ipcRenderer.invoke('depk:dynSandbox', { path, seconds }),
  pickFile: () => ipcRenderer.invoke('depk:pickFile'),
  onWatchEvent: (cb) => ipcRenderer.on('depk:watchEvent', (_e, d) => cb(d)),
  getStatus: () => ipcRenderer.invoke('setup:getStatus'),
  install: (dir, autostart) => ipcRenderer.invoke('setup:install', { dir, autostart }),
  uninstall: () => ipcRenderer.invoke('setup:uninstall'),
  launchInstalled: () => ipcRenderer.invoke('setup:launchInstalled'),
  minWin: () => ipcRenderer.send('win:min'),
  closeWin: () => ipcRenderer.send('win:close'),
  onProgress: (cb) => ipcRenderer.on('setup:progress', (_e, d) => cb(d)),
  uninstallApp: (cmd, quiet) => ipcRenderer.invoke('depk:uninstallApp', { cmd, quiet }),
  forceRemove: (key, name, location) => ipcRenderer.invoke('depk:forceRemove', { key, name, location }),
  scanResidual: (name, location) => ipcRenderer.invoke('depk:scanResidual', { name, location }),
  deleteResidual: (paths) => ipcRenderer.invoke('depk:deleteResidual', { paths }),
  openLocation: (p) => ipcRenderer.invoke('depk:openLocation', p),
  copyText: (t) => ipcRenderer.invoke('depk:copyText', t)
});
